AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - test/**/*

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
